// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicDBPlayground.DiscogsIntegration.Data;

#nullable disable

namespace MusicDBPlayground.DiscogsIntegration.Migrations
{
    [DbContext(typeof(DiscogsDbContext))]
    partial class DiscogsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("MusicDBPlayground.DiscogsIntegration.Data.OAuthTokenEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EncryptedToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedTokenSecret")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OAuthTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
